CREATE DATABASE `tp_bdd_28_9`;
USE `tp_bdd_28_9`;

CREATE TABLE `cliente` (
	`ID_CLIENTE` INT(11) NOT NULL,
	`NOMBRE_COMPAÑIA` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`NOMBRE_CONTACTO` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`CARGO_CONTACTO` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`DIRECCION` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`CIUDAD` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`REGION` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`CODPOSTAL` INT(11) NOT NULL DEFAULT '0',
	`PAIS` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'latin1_swedish_ci',
	`TELEFONO` INT(11) NOT NULL DEFAULT '0',
	`FAX` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID_CLIENTE`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `compañia_envios` (
	`ID_COMPAÑIA` INT(11) NOT NULL,
	`NOMBRE_COMPAÑIA` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`TELEFONO` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID_COMPAÑIA`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `empleado` (
	`ID_EMPLEADO` INT(11) NOT NULL,
	`APELLIDOS` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`NOMBRE` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`CARGO` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`TRATAMIENTO` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`FECHA_NACIMIENTO` DATE NOT NULL,
	`FECHA_CONTRATACION` DATE NOT NULL,
	`DIRECCION` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`CIUDAD` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`REGION` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`COD_POSTAL` INT(11) NOT NULL DEFAULT '0',
	`PAIS` VARCHAR(50) NOT NULL COLLATE 'latin1_swedish_ci',
	`EXTENSION` VARCHAR(50) NOT NULL COLLATE 'latin1_swedish_ci',
	`TEL_DOMICILIO` INT(11) NOT NULL DEFAULT '0',
	`FOTO` LONGTEXT NOT NULL DEFAULT '0' COLLATE 'utf8mb4_bin',
	`NOTAS` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'latin1_swedish_ci',
	`JEFE` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`ID_EMPLEADO`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `producto` (
	`ID_PRODUCTO` INT(11) NOT NULL,
	`NOMBRE_PRODUCTO` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`CANTIDAD_X_UNIDAD` INT(11) NOT NULL,
	`PRECIO_UNIDAD` INT(11) NOT NULL,
	PRIMARY KEY (`ID_PRODUCTO`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `detalle_pedido` (
	`DETALLE_PEDIDO` INT(11) NOT NULL,
	`PRECIO_UNIDAD` INT(11) NOT NULL,
	`CANTIDAD` INT(11) NOT NULL,
	`DESCUENTO` INT(11) NOT NULL,
	`ID_PEDIDO` INT(11) NOT NULL,
	`ID_PRODUCTO` INT(11) NOT NULL,
	PRIMARY KEY (`DETALLE_PEDIDO`) USING BTREE,
	INDEX `FK_detalle_pedido_producto` (`ID_PRODUCTO`) USING BTREE,
	CONSTRAINT `FK_detalle_pedido_producto` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `tp_bdd_28_9`.`producto` (`ID_PRODUCTO`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


